(module
(memory (export "memory") 1)
(func $mm (param $d i32) (param $a i32) (param $b i32)
(local $a0 i64) (local $b0 i64) (local $n0 i64) (local $a1 i64) (local $b1 i64) (local $n1 i64) (local $a2 i64) (local $b2 i64) (local $n2 i64) (local $a3 i64) (local $b3 i64) (local $n3 i64) (local $a4 i64) (local $b4 i64) (local $n4 i64) (local $a5 i64) (local $b5 i64) (local $n5 i64) (local $a6 i64) (local $b6 i64) (local $n6 i64) (local $a7 i64) (local $b7 i64) (local $n7 i64) (local $t0 i64) (local $t1 i64) (local $t2 i64) (local $t3 i64) (local $t4 i64) (local $t5 i64) (local $t6 i64) (local $t7 i64) (local $t8 i64) (local $t9 i64) (local $c i64) (local $m i64) (local $x i64) (local $np i64)
(local.set $a0 (i64.load32_u offset=0 (local.get $a)))
(local.set $b0 (i64.load32_u offset=0 (local.get $b)))
(local.set $n0 (i64.load32_u offset=0 (i32.const 0)))
(local.set $a1 (i64.load32_u offset=4 (local.get $a)))
(local.set $b1 (i64.load32_u offset=4 (local.get $b)))
(local.set $n1 (i64.load32_u offset=4 (i32.const 0)))
(local.set $a2 (i64.load32_u offset=8 (local.get $a)))
(local.set $b2 (i64.load32_u offset=8 (local.get $b)))
(local.set $n2 (i64.load32_u offset=8 (i32.const 0)))
(local.set $a3 (i64.load32_u offset=12 (local.get $a)))
(local.set $b3 (i64.load32_u offset=12 (local.get $b)))
(local.set $n3 (i64.load32_u offset=12 (i32.const 0)))
(local.set $a4 (i64.load32_u offset=16 (local.get $a)))
(local.set $b4 (i64.load32_u offset=16 (local.get $b)))
(local.set $n4 (i64.load32_u offset=16 (i32.const 0)))
(local.set $a5 (i64.load32_u offset=20 (local.get $a)))
(local.set $b5 (i64.load32_u offset=20 (local.get $b)))
(local.set $n5 (i64.load32_u offset=20 (i32.const 0)))
(local.set $a6 (i64.load32_u offset=24 (local.get $a)))
(local.set $b6 (i64.load32_u offset=24 (local.get $b)))
(local.set $n6 (i64.load32_u offset=24 (i32.const 0)))
(local.set $a7 (i64.load32_u offset=28 (local.get $a)))
(local.set $b7 (i64.load32_u offset=28 (local.get $b)))
(local.set $n7 (i64.load32_u offset=28 (i32.const 0)))
(local.set $np (i64.load32_u offset=96 (i32.const 0)))
(local.set $c (i64.const 0))
(local.set $x (i64.add (i64.add (local.get $t0) (i64.mul (local.get $a0) (local.get $b0))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $a1) (local.get $b0))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $a2) (local.get $b0))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $a3) (local.get $b0))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $a4) (local.get $b0))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $a5) (local.get $b0))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $a6) (local.get $b0))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $a7) (local.get $b0))) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t8 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t9 (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $m (i64.and (i64.mul (local.get $t0) (local.get $np)) (i64.const 0xffffffff)))
(local.set $x (i64.add (local.get $t0) (i64.mul (local.get $m) (local.get $n0))))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $m) (local.get $n1))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $m) (local.get $n2))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $m) (local.get $n3))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $m) (local.get $n4))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $m) (local.get $n5))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $m) (local.get $n6))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $m) (local.get $n7))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t8 (i64.add (local.get $t9) (i64.shr_u (local.get $x) (i64.const 32))))
(local.set $c (i64.const 0))
(local.set $x (i64.add (i64.add (local.get $t0) (i64.mul (local.get $a0) (local.get $b1))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $a1) (local.get $b1))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $a2) (local.get $b1))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $a3) (local.get $b1))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $a4) (local.get $b1))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $a5) (local.get $b1))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $a6) (local.get $b1))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $a7) (local.get $b1))) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t8 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t9 (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $m (i64.and (i64.mul (local.get $t0) (local.get $np)) (i64.const 0xffffffff)))
(local.set $x (i64.add (local.get $t0) (i64.mul (local.get $m) (local.get $n0))))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $m) (local.get $n1))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $m) (local.get $n2))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $m) (local.get $n3))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $m) (local.get $n4))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $m) (local.get $n5))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $m) (local.get $n6))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $m) (local.get $n7))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t8 (i64.add (local.get $t9) (i64.shr_u (local.get $x) (i64.const 32))))
(local.set $c (i64.const 0))
(local.set $x (i64.add (i64.add (local.get $t0) (i64.mul (local.get $a0) (local.get $b2))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $a1) (local.get $b2))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $a2) (local.get $b2))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $a3) (local.get $b2))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $a4) (local.get $b2))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $a5) (local.get $b2))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $a6) (local.get $b2))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $a7) (local.get $b2))) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t8 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t9 (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $m (i64.and (i64.mul (local.get $t0) (local.get $np)) (i64.const 0xffffffff)))
(local.set $x (i64.add (local.get $t0) (i64.mul (local.get $m) (local.get $n0))))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $m) (local.get $n1))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $m) (local.get $n2))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $m) (local.get $n3))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $m) (local.get $n4))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $m) (local.get $n5))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $m) (local.get $n6))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $m) (local.get $n7))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t8 (i64.add (local.get $t9) (i64.shr_u (local.get $x) (i64.const 32))))
(local.set $c (i64.const 0))
(local.set $x (i64.add (i64.add (local.get $t0) (i64.mul (local.get $a0) (local.get $b3))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $a1) (local.get $b3))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $a2) (local.get $b3))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $a3) (local.get $b3))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $a4) (local.get $b3))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $a5) (local.get $b3))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $a6) (local.get $b3))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $a7) (local.get $b3))) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t8 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t9 (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $m (i64.and (i64.mul (local.get $t0) (local.get $np)) (i64.const 0xffffffff)))
(local.set $x (i64.add (local.get $t0) (i64.mul (local.get $m) (local.get $n0))))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $m) (local.get $n1))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $m) (local.get $n2))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $m) (local.get $n3))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $m) (local.get $n4))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $m) (local.get $n5))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $m) (local.get $n6))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $m) (local.get $n7))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t8 (i64.add (local.get $t9) (i64.shr_u (local.get $x) (i64.const 32))))
(local.set $c (i64.const 0))
(local.set $x (i64.add (i64.add (local.get $t0) (i64.mul (local.get $a0) (local.get $b4))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $a1) (local.get $b4))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $a2) (local.get $b4))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $a3) (local.get $b4))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $a4) (local.get $b4))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $a5) (local.get $b4))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $a6) (local.get $b4))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $a7) (local.get $b4))) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t8 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t9 (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $m (i64.and (i64.mul (local.get $t0) (local.get $np)) (i64.const 0xffffffff)))
(local.set $x (i64.add (local.get $t0) (i64.mul (local.get $m) (local.get $n0))))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $m) (local.get $n1))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $m) (local.get $n2))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $m) (local.get $n3))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $m) (local.get $n4))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $m) (local.get $n5))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $m) (local.get $n6))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $m) (local.get $n7))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t8 (i64.add (local.get $t9) (i64.shr_u (local.get $x) (i64.const 32))))
(local.set $c (i64.const 0))
(local.set $x (i64.add (i64.add (local.get $t0) (i64.mul (local.get $a0) (local.get $b5))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $a1) (local.get $b5))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $a2) (local.get $b5))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $a3) (local.get $b5))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $a4) (local.get $b5))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $a5) (local.get $b5))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $a6) (local.get $b5))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $a7) (local.get $b5))) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t8 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t9 (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $m (i64.and (i64.mul (local.get $t0) (local.get $np)) (i64.const 0xffffffff)))
(local.set $x (i64.add (local.get $t0) (i64.mul (local.get $m) (local.get $n0))))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $m) (local.get $n1))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $m) (local.get $n2))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $m) (local.get $n3))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $m) (local.get $n4))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $m) (local.get $n5))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $m) (local.get $n6))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $m) (local.get $n7))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t8 (i64.add (local.get $t9) (i64.shr_u (local.get $x) (i64.const 32))))
(local.set $c (i64.const 0))
(local.set $x (i64.add (i64.add (local.get $t0) (i64.mul (local.get $a0) (local.get $b6))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $a1) (local.get $b6))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $a2) (local.get $b6))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $a3) (local.get $b6))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $a4) (local.get $b6))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $a5) (local.get $b6))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $a6) (local.get $b6))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $a7) (local.get $b6))) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t8 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t9 (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $m (i64.and (i64.mul (local.get $t0) (local.get $np)) (i64.const 0xffffffff)))
(local.set $x (i64.add (local.get $t0) (i64.mul (local.get $m) (local.get $n0))))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $m) (local.get $n1))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $m) (local.get $n2))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $m) (local.get $n3))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $m) (local.get $n4))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $m) (local.get $n5))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $m) (local.get $n6))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $m) (local.get $n7))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t8 (i64.add (local.get $t9) (i64.shr_u (local.get $x) (i64.const 32))))
(local.set $c (i64.const 0))
(local.set $x (i64.add (i64.add (local.get $t0) (i64.mul (local.get $a0) (local.get $b7))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $a1) (local.get $b7))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $a2) (local.get $b7))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $a3) (local.get $b7))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $a4) (local.get $b7))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $a5) (local.get $b7))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $a6) (local.get $b7))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $a7) (local.get $b7))) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t8 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t9 (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $m (i64.and (i64.mul (local.get $t0) (local.get $np)) (i64.const 0xffffffff)))
(local.set $x (i64.add (local.get $t0) (i64.mul (local.get $m) (local.get $n0))))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t1) (i64.mul (local.get $m) (local.get $n1))) (local.get $c)))
(local.set $t0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t2) (i64.mul (local.get $m) (local.get $n2))) (local.get $c)))
(local.set $t1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t3) (i64.mul (local.get $m) (local.get $n3))) (local.get $c)))
(local.set $t2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t4) (i64.mul (local.get $m) (local.get $n4))) (local.get $c)))
(local.set $t3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t5) (i64.mul (local.get $m) (local.get $n5))) (local.get $c)))
(local.set $t4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t6) (i64.mul (local.get $m) (local.get $n6))) (local.get $c)))
(local.set $t5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (local.get $t7) (i64.mul (local.get $m) (local.get $n7))) (local.get $c)))
(local.set $t6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (local.get $t8) (local.get $c)))
(local.set $t7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $t8 (i64.add (local.get $t9) (i64.shr_u (local.get $x) (i64.const 32))))
(local.set $a0 (local.get $t0))
(local.set $a1 (local.get $t1))
(local.set $a2 (local.get $t2))
(local.set $a3 (local.get $t3))
(local.set $a4 (local.get $t4))
(local.set $a5 (local.get $t5))
(local.set $a6 (local.get $t6))
(local.set $a7 (local.get $t7))
(local.set $c (i64.const 0))
(local.set $x (i64.sub (i64.sub (local.get $t0) (local.get $n0)) (local.get $c)))
(local.set $a0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $t1) (local.get $n1)) (local.get $c)))
(local.set $a1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $t2) (local.get $n2)) (local.get $c)))
(local.set $a2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $t3) (local.get $n3)) (local.get $c)))
(local.set $a3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $t4) (local.get $n4)) (local.get $c)))
(local.set $a4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $t5) (local.get $n5)) (local.get $c)))
(local.set $a5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $t6) (local.get $n6)) (local.get $c)))
(local.set $a6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $t7) (local.get $n7)) (local.get $c)))
(local.set $a7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(if (i64.eqz (local.get $c)) (then
(local.set $t0 (local.get $a0))
(local.set $t1 (local.get $a1))
(local.set $t2 (local.get $a2))
(local.set $t3 (local.get $a3))
(local.set $t4 (local.get $a4))
(local.set $t5 (local.get $a5))
(local.set $t6 (local.get $a6))
(local.set $t7 (local.get $a7))
))
(i64.store32 offset=0 (local.get $d) (local.get $t0))
(i64.store32 offset=4 (local.get $d) (local.get $t1))
(i64.store32 offset=8 (local.get $d) (local.get $t2))
(i64.store32 offset=12 (local.get $d) (local.get $t3))
(i64.store32 offset=16 (local.get $d) (local.get $t4))
(i64.store32 offset=20 (local.get $d) (local.get $t5))
(i64.store32 offset=24 (local.get $d) (local.get $t6))
(i64.store32 offset=28 (local.get $d) (local.get $t7))
)
(func $add (param $d i32) (param $a i32) (param $b i32)
(local $s0 i64) (local $u0 i64) (local $s1 i64) (local $u1 i64) (local $s2 i64) (local $u2 i64) (local $s3 i64) (local $u3 i64) (local $s4 i64) (local $u4 i64) (local $s5 i64) (local $u5 i64) (local $s6 i64) (local $u6 i64) (local $s7 i64) (local $u7 i64) (local $c i64) (local $x i64)
(local.set $c (i64.const 0))
(local.set $x (i64.add (i64.add (i64.load32_u offset=0 (local.get $a)) (i64.load32_u offset=0 (local.get $b))) (local.get $c)))
(local.set $s0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (i64.load32_u offset=4 (local.get $a)) (i64.load32_u offset=4 (local.get $b))) (local.get $c)))
(local.set $s1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (i64.load32_u offset=8 (local.get $a)) (i64.load32_u offset=8 (local.get $b))) (local.get $c)))
(local.set $s2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (i64.load32_u offset=12 (local.get $a)) (i64.load32_u offset=12 (local.get $b))) (local.get $c)))
(local.set $s3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (i64.load32_u offset=16 (local.get $a)) (i64.load32_u offset=16 (local.get $b))) (local.get $c)))
(local.set $s4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (i64.load32_u offset=20 (local.get $a)) (i64.load32_u offset=20 (local.get $b))) (local.get $c)))
(local.set $s5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (i64.load32_u offset=24 (local.get $a)) (i64.load32_u offset=24 (local.get $b))) (local.get $c)))
(local.set $s6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $x (i64.add (i64.add (i64.load32_u offset=28 (local.get $a)) (i64.load32_u offset=28 (local.get $b))) (local.get $c)))
(local.set $s7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
(local.set $c (i64.const 0))
(local.set $x (i64.sub (i64.sub (local.get $s0) (i64.load32_u offset=0 (i32.const 0))) (local.get $c)))
(local.set $u0 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $s1) (i64.load32_u offset=4 (i32.const 0))) (local.get $c)))
(local.set $u1 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $s2) (i64.load32_u offset=8 (i32.const 0))) (local.get $c)))
(local.set $u2 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $s3) (i64.load32_u offset=12 (i32.const 0))) (local.get $c)))
(local.set $u3 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $s4) (i64.load32_u offset=16 (i32.const 0))) (local.get $c)))
(local.set $u4 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $s5) (i64.load32_u offset=20 (i32.const 0))) (local.get $c)))
(local.set $u5 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $s6) (i64.load32_u offset=24 (i32.const 0))) (local.get $c)))
(local.set $u6 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(local.set $x (i64.sub (i64.sub (local.get $s7) (i64.load32_u offset=28 (i32.const 0))) (local.get $c)))
(local.set $u7 (i64.and (local.get $x) (i64.const 0xffffffff)))
(local.set $c (i64.shr_u (local.get $x) (i64.const 63)))
(if (i64.eqz (local.get $c)) (then
(local.set $s0 (local.get $u0))
(local.set $s1 (local.get $u1))
(local.set $s2 (local.get $u2))
(local.set $s3 (local.get $u3))
(local.set $s4 (local.get $u4))
(local.set $s5 (local.get $u5))
(local.set $s6 (local.get $u6))
(local.set $s7 (local.get $u7))
))
(i64.store32 offset=0 (local.get $d) (local.get $s0))
(i64.store32 offset=4 (local.get $d) (local.get $s1))
(i64.store32 offset=8 (local.get $d) (local.get $s2))
(i64.store32 offset=12 (local.get $d) (local.get $s3))
(i64.store32 offset=16 (local.get $d) (local.get $s4))
(i64.store32 offset=20 (local.get $d) (local.get $s5))
(i64.store32 offset=24 (local.get $d) (local.get $s6))
(i64.store32 offset=28 (local.get $d) (local.get $s7))
)
(func $copy (param $d i32) (param $s i32)
  (i64.store offset=0 (local.get $d) (i64.load offset=0 (local.get $s)))
  (i64.store offset=8 (local.get $d) (i64.load offset=8 (local.get $s)))
  (i64.store offset=16 (local.get $d) (i64.load offset=16 (local.get $s)))
  (i64.store offset=24 (local.get $d) (i64.load offset=24 (local.get $s))))
(func $zero (param $d i32)
  (i64.store offset=0 (local.get $d) (i64.const 0))
  (i64.store offset=8 (local.get $d) (i64.const 0))
  (i64.store offset=16 (local.get $d) (i64.const 0))
  (i64.store offset=24 (local.get $d) (i64.const 0)))
;; STATE[0..t) <- M * STATE (M row-major t*t at $mp)
(func $mix (param $t i32) (param $mp i32)
  (local $i i32) (local $j i32) (local $row i32)
  (local.set $i (i32.const 0))
  (block $md (loop $ml
    (br_if $md (i32.ge_u (local.get $i) (local.get $t)))
    (local.set $row (i32.add (local.get $mp) (i32.shl (i32.mul (local.get $i) (local.get $t)) (i32.const 5))))
    (call $mm (i32.add (i32.const 704) (i32.shl (local.get $i) (i32.const 5))) (local.get $row) (i32.const 512))
    (local.set $j (i32.const 1))
    (block $jd (loop $jl
      (br_if $jd (i32.ge_u (local.get $j) (local.get $t)))
      (call $mm (i32.const 192) (i32.add (local.get $row) (i32.shl (local.get $j) (i32.const 5))) (i32.add (i32.const 512) (i32.shl (local.get $j) (i32.const 5))))
      (call $add (i32.add (i32.const 704) (i32.shl (local.get $i) (i32.const 5))) (i32.add (i32.const 704) (i32.shl (local.get $i) (i32.const 5))) (i32.const 192))
      (local.set $j (i32.add (local.get $j) (i32.const 1)))
      (br $jl)))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br $ml)))
  (memory.copy (i32.const 512) (i32.const 704) (i32.shl (local.get $t) (i32.const 5))))
;; full round: add constants (t at $cp), s-box all, mix
(func $fullRound (param $t i32) (param $cp i32) (param $mp i32)
  (local $i i32)
  (local.set $i (i32.const 0))
  (block $d (loop $l
    (br_if $d (i32.ge_u (local.get $i) (local.get $t)))
    (call $add (i32.add (i32.const 512) (i32.shl (local.get $i) (i32.const 5))) (i32.add (i32.const 512) (i32.shl (local.get $i) (i32.const 5))) (i32.add (local.get $cp) (i32.shl (local.get $i) (i32.const 5))))
    (call $pow5 (i32.add (i32.const 512) (i32.shl (local.get $i) (i32.const 5))))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br $l)))
  (call $mix (local.get $t) (local.get $mp)))
;; Optimized permutation. Layout at $op: FC[8*t] | A[rp] | SP[rp*(2t-1)] | ML[t*t]
(func $permOpt (param $t i32) (param $rp i32) (param $op i32) (param $mp i32)
  (local $r i32) (local $a i32) (local $sp i32) (local $ml i32) (local $j i32) (local $w i32)
  (local.set $a (i32.add (local.get $op) (i32.shl (i32.mul (i32.const 8) (local.get $t)) (i32.const 5))))
  (local.set $sp (i32.add (local.get $a) (i32.shl (local.get $rp) (i32.const 5))))
  (local.set $ml (i32.add (local.get $sp) (i32.shl (i32.mul (local.get $rp) (i32.sub (i32.shl (local.get $t) (i32.const 1)) (i32.const 1))) (i32.const 5))))
  (local.set $r (i32.const 0))
  (block $d1 (loop $l1
    (br_if $d1 (i32.ge_u (local.get $r) (i32.const 4)))
    (call $fullRound (local.get $t) (i32.add (local.get $op) (i32.shl (i32.mul (local.get $r) (local.get $t)) (i32.const 5))) (local.get $mp))
    (local.set $r (i32.add (local.get $r) (i32.const 1)))
    (br $l1)))
  ;; partial rounds with scalar constants and sparse mixes
  (local.set $r (i32.const 0))
  (block $d2 (loop $l2
    (br_if $d2 (i32.ge_u (local.get $r) (local.get $rp)))
    (call $add (i32.const 512) (i32.const 512) (i32.add (local.get $a) (i32.shl (local.get $r) (i32.const 5))))
    (call $pow5 (i32.const 512))
    ;; new s0 (into MIX[0]) = sp[0]*s0 + sum_j sp[j]*s_j
    (call $mm (i32.const 704) (local.get $sp) (i32.const 512))
    (local.set $j (i32.const 1))
    (block $jd (loop $jl
      (br_if $jd (i32.ge_u (local.get $j) (local.get $t)))
      (call $mm (i32.const 192) (i32.add (local.get $sp) (i32.shl (local.get $j) (i32.const 5))) (i32.add (i32.const 512) (i32.shl (local.get $j) (i32.const 5))))
      (call $add (i32.const 704) (i32.const 704) (i32.const 192))
      (local.set $j (i32.add (local.get $j) (i32.const 1)))
      (br $jl)))
    ;; s_j += w_j * s0 (old s0)
    (local.set $w (i32.add (local.get $sp) (i32.shl (i32.sub (local.get $t) (i32.const 1)) (i32.const 5))))
    (local.set $j (i32.const 1))
    (block $kd (loop $kl
      (br_if $kd (i32.ge_u (local.get $j) (local.get $t)))
      (call $mm (i32.const 192) (i32.add (local.get $w) (i32.shl (local.get $j) (i32.const 5))) (i32.const 512))
      (call $add (i32.add (i32.const 512) (i32.shl (local.get $j) (i32.const 5))) (i32.add (i32.const 512) (i32.shl (local.get $j) (i32.const 5))) (i32.const 192))
      (local.set $j (i32.add (local.get $j) (i32.const 1)))
      (br $kl)))
    (call $copy (i32.const 512) (i32.const 704))
    (local.set $sp (i32.add (local.get $sp) (i32.shl (i32.sub (i32.shl (local.get $t) (i32.const 1)) (i32.const 1)) (i32.const 5))))
    (local.set $r (i32.add (local.get $r) (i32.const 1)))
    (br $l2)))
  ;; deferred dense block
  (call $mix (local.get $t) (local.get $ml))
  (local.set $r (i32.const 4))
  (block $d3 (loop $l3
    (br_if $d3 (i32.ge_u (local.get $r) (i32.const 8)))
    (call $fullRound (local.get $t) (i32.add (local.get $op) (i32.shl (i32.mul (local.get $r) (local.get $t)) (i32.const 5))) (local.get $mp))
    (local.set $r (i32.add (local.get $r) (i32.const 1)))
    (br $l3))))
;; x <- x^5 (Montgomery)
(func $pow5 (param $x i32)
  (call $mm (i32.const 128) (local.get $x) (local.get $x))
  (call $mm (i32.const 160) (i32.const 128) (i32.const 128))
  (call $mm (local.get $x) (i32.const 160) (local.get $x)))
;; Poseidon permutation on STATE[0..t)
(func $perm (param $t i32) (param $rp i32) (param $cp i32) (param $mp i32)
  (local $r i32) (local $i i32) (local $j i32) (local $total i32) (local $full i32) (local $row i32)
  (local.set $total (i32.add (local.get $rp) (i32.const 8)))
  (local.set $r (i32.const 0))
  (block $done (loop $round
    (br_if $done (i32.ge_u (local.get $r) (local.get $total)))
    ;; add round constants
    (local.set $i (i32.const 0))
    (block $ad (loop $al
      (br_if $ad (i32.ge_u (local.get $i) (local.get $t)))
      (call $add
        (i32.add (i32.const 512) (i32.shl (local.get $i) (i32.const 5)))
        (i32.add (i32.const 512) (i32.shl (local.get $i) (i32.const 5)))
        (i32.add (local.get $cp) (i32.shl (i32.add (i32.mul (local.get $r) (local.get $t)) (local.get $i)) (i32.const 5))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $al)))
    ;; s-box: full rounds on all, partial on state[0]
    (local.set $full (i32.or (i32.lt_u (local.get $r) (i32.const 4)) (i32.ge_u (local.get $r) (i32.add (local.get $rp) (i32.const 4)))))
    (if (local.get $full)
      (then
        (local.set $i (i32.const 0))
        (block $sd (loop $sl
          (br_if $sd (i32.ge_u (local.get $i) (local.get $t)))
          (call $pow5 (i32.add (i32.const 512) (i32.shl (local.get $i) (i32.const 5))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $sl))))
      (else (call $pow5 (i32.const 512))))
    ;; mix: MIX[i] = sum_j M[i][j] * STATE[j]
    (local.set $i (i32.const 0))
    (block $md (loop $ml
      (br_if $md (i32.ge_u (local.get $i) (local.get $t)))
      (local.set $row (i32.add (local.get $mp) (i32.shl (i32.mul (local.get $i) (local.get $t)) (i32.const 5))))
      (call $mm (i32.add (i32.const 704) (i32.shl (local.get $i) (i32.const 5))) (local.get $row) (i32.const 512))
      (local.set $j (i32.const 1))
      (block $jd (loop $jl
        (br_if $jd (i32.ge_u (local.get $j) (local.get $t)))
        (call $mm (i32.const 192) (i32.add (local.get $row) (i32.shl (local.get $j) (i32.const 5))) (i32.add (i32.const 512) (i32.shl (local.get $j) (i32.const 5))))
        (call $add (i32.add (i32.const 704) (i32.shl (local.get $i) (i32.const 5))) (i32.add (i32.const 704) (i32.shl (local.get $i) (i32.const 5))) (i32.const 192))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br $jl)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $ml)))
    (memory.copy (i32.const 512) (i32.const 704) (i32.shl (local.get $t) (i32.const 5)))
    (local.set $r (i32.add (local.get $r) (i32.const 1)))
    (br $round)))
)
(func $toMont (param $d i32) (param $s i32) (call $mm (local.get $d) (local.get $s) (i32.const 32)))
(func $fromMont (param $d i32) (param $s i32) (call $mm (local.get $d) (local.get $s) (i32.const 64)))
(func $permT (param $t i32)
  (if (i32.load (i32.const 100))
    (then
      (if (i32.eq (local.get $t) (i32.const 4))
        (then (call $permOpt (i32.const 4) (i32.const 56) (i32.const 24576) (i32.const 10240)))
        (else (call $permOpt (i32.const 5) (i32.const 60) (i32.const 40960) (i32.const 22528)))))
    (else
      (if (i32.eq (local.get $t) (i32.const 4))
        (then (call $perm (i32.const 4) (i32.const 56) (i32.const 2048) (i32.const 10240)))
        (else (call $perm (i32.const 5) (i32.const 60) (i32.const 11264) (i32.const 22528)))))))
;; hash(t): IN[0..t-1) canonical -> OUT canonical. t = inputs + 1 (4 or 5).
(func (export "hash") (param $t i32)
  (local $i i32)
  (call $zero (i32.const 512))
  (local.set $i (i32.const 1))
  (block $d (loop $l
    (br_if $d (i32.ge_u (local.get $i) (local.get $t)))
    (call $toMont (i32.add (i32.const 512) (i32.shl (local.get $i) (i32.const 5))) (i32.add (i32.const 992) (i32.shl (local.get $i) (i32.const 5))))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br $l)))
  (call $permT (local.get $t))
  (call $fromMont (i32.const 1280) (i32.const 512)))
;; grind(count): IN = [TAG, digest, aura, nonce] canonical; THRESH canonical.
;; Returns the first i < count whose name hash h satisfies h < THRESH, with IN[3] left at that nonce; else -1 (IN[3] advanced by count).
(func (export "grind") (param $count i32) (result i32)
  (local $i i32) (local $k i32) (local $x i64) (local $c i64) (local $lt i32) (local $eq i32) (local $a i64) (local $b i64)
  (call $toMont (i32.const 1408) (i32.const 1024))
  (call $toMont (i32.const 1440) (i32.const 1056))
  (call $toMont (i32.const 1472) (i32.const 1088))
  (local.set $i (i32.const 0))
  (block $done (loop $l
    (br_if $done (i32.ge_u (local.get $i) (local.get $count)))
    (call $zero (i32.const 512))
    (memory.copy (i32.const 544) (i32.const 1408) (i32.const 96))
    (call $toMont (i32.const 640) (i32.const 1120))
    (call $permT (i32.const 5))
    (call $fromMont (i32.const 1280) (i32.const 512))
    ;; OUT < THRESH ? compare from the top limb down
    (local.set $lt (i32.const 0))
    (local.set $k (i32.const 7))
    (block $cd (loop $cl
      (local.set $a (i64.load32_u (i32.add (i32.const 1280) (i32.shl (local.get $k) (i32.const 2)))))
      (local.set $b (i64.load32_u (i32.add (i32.const 1344) (i32.shl (local.get $k) (i32.const 2)))))
      (if (i64.lt_u (local.get $a) (local.get $b)) (then (local.set $lt (i32.const 1)) (br $cd)))
      (br_if $cd (i64.gt_u (local.get $a) (local.get $b)))
      (br_if $cd (i32.eqz (local.get $k)))
      (local.set $k (i32.sub (local.get $k) (i32.const 1)))
      (br $cl)))
    (if (local.get $lt) (then (return (local.get $i))))
    ;; nonce += 1 (carry through all limbs)
    (local.set $c (i64.const 1))
    (local.set $k (i32.const 0))
    (block $id (loop $il
      (br_if $id (i64.eqz (local.get $c)))
      (br_if $id (i32.ge_u (local.get $k) (i32.const 8)))
      (local.set $x (i64.add (i64.load32_u (i32.add (i32.const 1120) (i32.shl (local.get $k) (i32.const 2)))) (local.get $c)))
      (i64.store32 (i32.add (i32.const 1120) (i32.shl (local.get $k) (i32.const 2))) (local.get $x))
      (local.set $c (i64.shr_u (local.get $x) (i64.const 32)))
      (local.set $k (i32.add (local.get $k) (i32.const 1)))
      (br $il)))
    (local.set $i (i32.add (local.get $i) (i32.const 1)))
    (br $l)))
  (i32.const -1))
)