// Generates circuits/name.circom: "I hold a name of at least `strength` truths on a spirit
// of magnitude at least `magnitude`, with this element and these traits (form, weight,
// generosity, temper)" without revealing the spirit's address (digits, depth), its trait hash,
// or the nonce. A per-round tag identifies the spirit within one round only.
// Constants (seed, tags, P>>k thresholds) come from the universe so the circuit can't drift from spec v1.
import { P, SEED, TAG_CELL, TAG_SPIRIT, TAG_TRAITS, TAG_NAME, MIN_SPIRIT_DEPTH } from '@truenames/universe';

/** Deepest provable spirit. Deeper spirits need a bigger circuit. */
export const MAX_DEPTH = 24;
/** Thresholds table size: truths/bits provable up to K-1. */
export const K = 64;
/**
 * Domain tag for the per-round spirit tag. A proof-system tag, not a universe tag: it must never
 * collide with the universe's (1..5), and changing it only invalidates in-flight proofs.
 */
export const TAG_ROUND = 101n;

export function circuitSource(): string {
  const split = (x: bigint) => ({ hi: x >> 127n, lo: x & ((1n << 127n) - 1n) });
  const hi: string[] = [], lo: string[] = [];
  for (let k = 0; k < K; k++) {
    const t = split(P >> BigInt(k)); // bits(h) >= k  <=>  h < (P >> k)
    hi.push(t.hi.toString());
    lo.push(t.lo.toString());
  }
  return `pragma circom 2.1.0;
// GENERATED by packages/proofs/src/gen-circuit.ts. Do not edit.
include "circomlib/circuits/poseidon.circom";
include "circomlib/circuits/bitify.circom";
include "circomlib/circuits/comparators.circom";

// Enforces bits(h) >= k, where bits(h) = largest k with (h+1)*2^k <= P  (spec v1),
// i.e. h < floor(P / 2^k). k is a signal in [0, ${K}).
template AtLeastBits() {
    signal input h;
    signal input k;
    var THI[${K}] = [${hi.join(', ')}];
    var TLO[${K}] = [${lo.join(', ')}];

    // one-hot select of the threshold for k
    component eq[${K}];
    signal sel[${K}];
    var any = 0;
    var tHi = 0;
    var tLo = 0;
    for (var i = 0; i < ${K}; i++) {
        eq[i] = IsEqual();
        eq[i].in[0] <== k;
        eq[i].in[1] <== i;
        sel[i] <== eq[i].out;
        any += sel[i];
        tHi += sel[i] * THI[i];
        tLo += sel[i] * TLO[i];
    }
    any === 1; // k must be in range

    // canonical bits of h, split into 127-bit halves
    component hb = Num2Bits_strict();
    hb.in <== h;
    var hHi = 0;
    var hLo = 0;
    for (var i = 0; i < 127; i++) { hLo += hb.out[i] * (1 << i); }
    for (var i = 127; i < 254; i++) { hHi += hb.out[i] * (1 << (i - 127)); }

    // h < t  <=>  hHi < tHi  or  (hHi == tHi and hLo < tLo)
    component ltHi = LessThan(128);
    ltHi.in[0] <== hHi;
    ltHi.in[1] <== tHi;
    component eqHi = IsEqual();
    eqHi.in[0] <== hHi;
    eqHi.in[1] <== tHi;
    component ltLo = LessThan(128);
    ltLo.in[0] <== hLo;
    ltLo.in[1] <== tLo;
    signal both;
    both <== eqHi.out * ltLo.out;
    ltHi.out + both === 1; // exactly one can hold when true; both 0 means h >= t
}

template NameClaim(MAXD) {
    // --- secrets (never leave the sanctum) ---
    signal input digits[MAXD];   // the spirit's address, octal digits
    signal input depth;          // its depth
    signal input nonce;          // your name

    // --- public inputs ---
    signal input aura;           // auraField(your public key)
    signal input magnitude;      // claimed at least this mighty
    signal input strength;       // claimed at least this many truths
    signal input context;        // binds the proof to one journey

    // --- public outputs: the details, never the source ---
    signal output roundTag;      // this spirit, in this round only (unlinkable across rounds)
    signal output element;       // first address digit
    signal output form;          // traits: the low bits of the trait hash (the hash itself stays secret)
    signal output weightIdx;
    signal output generosityIdx;
    signal output temperIdx;

    // digits are octal
    component dbits[MAXD];
    for (var i = 0; i < MAXD; i++) {
        dbits[i] = Num2Bits(3);
        dbits[i].in <== digits[i];
    }
    // ${MIN_SPIRIT_DEPTH} <= depth <= MAXD
    component dmin = GreaterEqThan(8);
    dmin.in[0] <== depth;
    dmin.in[1] <== ${MIN_SPIRIT_DEPTH};
    dmin.out === 1;
    component dmax = LessEqThan(8);
    dmax.in[0] <== depth;
    dmax.in[1] <== MAXD;
    dmax.out === 1;

    // chained cell digest over the first \`depth\` digits
    component step[MAXD];
    component active[MAXD];
    signal acc[MAXD + 1];
    acc[0] <== 0;
    for (var i = 0; i < MAXD; i++) {
        step[i] = Poseidon(3);
        step[i].inputs[0] <== ${TAG_CELL};
        step[i].inputs[1] <== acc[i];
        step[i].inputs[2] <== digits[i];
        active[i] = LessThan(8);
        active[i].in[0] <== i;
        active[i].in[1] <== depth;
        acc[i + 1] <== acc[i] + active[i].out * (step[i].out - acc[i]);
    }
    signal digest;
    digest <== acc[MAXD];

    // spirit existence and magnitude: bits(spiritHash) >= target(depth) + magnitude
    component sh = Poseidon(3);
    sh.inputs[0] <== ${TAG_SPIRIT};
    sh.inputs[1] <== ${SEED};
    sh.inputs[2] <== digest;
    // target(d) = 4 + floor(3d/2): d = 2q + r
    signal q;
    signal r;
    q <-- depth \\ 2;
    r <-- depth % 2;
    r * (r - 1) === 0;
    depth === 2 * q + r;
    component qbits = Num2Bits(5);
    qbits.in <== q;
    component mbits = Num2Bits(6);
    mbits.in <== magnitude;
    component spiritOk = AtLeastBits();
    spiritOk.h <== sh.out;
    spiritOk.k <== 4 + 3 * q + r + magnitude;

    // traits: decoded from the trait hash in-circuit; only the gameplay fields leave
    component th = Poseidon(3);
    th.inputs[0] <== ${TAG_TRAITS};
    th.inputs[1] <== ${SEED};
    th.inputs[2] <== digest;
    component tb = Num2Bits_strict();
    tb.in <== th.out;
    form <== tb.out[0] + 2 * tb.out[1] + 4 * tb.out[2];
    weightIdx <== tb.out[3] + 2 * tb.out[4] + 4 * tb.out[5] + 8 * tb.out[6];
    generosityIdx <== tb.out[7] + 2 * tb.out[8] + 4 * tb.out[9] + 8 * tb.out[10];
    temperIdx <== tb.out[11] + 2 * tb.out[12] + 4 * tb.out[13];
    element <== digits[0];

    // round tag: identifies the spirit within this round (duplicates, "shared patron" checks) and no further
    component rt = Poseidon(3);
    rt.inputs[0] <== ${TAG_ROUND};
    rt.inputs[1] <== digest;
    rt.inputs[2] <== context;
    roundTag <== rt.out;

    // the name: bits(nameHash(digest, aura, nonce)) >= strength
    component nh = Poseidon(4);
    nh.inputs[0] <== ${TAG_NAME};
    nh.inputs[1] <== digest;
    nh.inputs[2] <== aura;
    nh.inputs[3] <== nonce;
    component nameOk = AtLeastBits();
    nameOk.h <== nh.out;
    nameOk.k <== strength;

    // (the context is bound by the round tag above)
}

component main { public [aura, magnitude, strength, context] } = NameClaim(${MAX_DEPTH});
`;
}
