#!/usr/bin/env python3
"""
Token-cycling character mixer.

Each token is generated by the next character in the rotation, cycling
through the list. The KV cache is maintained across character switches,
so prior tokens (generated by different characters) are always in context.

--chunk N means each character generates N consecutive tokens before switching.
chunk=1 is pure per-token cycling; chunk=20 is more like "passages".

Usage:
    python mix.py "cynic,observer,scientist" "The ocean is"
    python mix.py "accountant,bureaucrat" --chunk 5 "When I was young,"
    python mix.py --all-combos   # run full experiment suite

Output saved to mix-results.json (resumable).
"""

import argparse
import itertools
import json
import os
import sys
import time
import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer

MODEL = "Qwen/Qwen2.5-1.5B-Instruct"
CHARS_FILE = os.path.join(os.path.dirname(__file__), "characters.json")
DEFAULT_OUTPUT = os.path.join(os.path.dirname(__file__), "mix-results.json")
MAX_TOKENS = 80
TOP_P = 0.9
REP_PENALTY = 1.15
SEED = 42

# two prompts to keep runtime reasonable — no KV cache means O(n^2) tokens
PROMPTS = [
    "The ocean is",
    "When I was young,",
]

CHUNK_SIZES = [1, 10]

# Curated experiment combos
COMBOS = [
    # user's original idea
    ["cynic", "observer", "scientist"],
    # all Tier A
    ["accountant", "scientist", "bureaucrat"],
    # all Tier B
    ["mourner", "nostalgist", "naturalist", "observer"],
    # all Tier C
    ["cynic", "activist", "eulogist"],
    # memory/grief
    ["mourner", "nostalgist"],
    # sardonic + formal
    ["cynic", "bureaucrat"],
    # analytical squared
    ["observer", "scientist"],
    # dark trio
    ["mourner", "eulogist", "cynic"],
    # nature + death
    ["naturalist", "eulogist"],
    # money vs nature clash
    ["accountant", "naturalist"],
    # precision + grief
    ["scientist", "mourner"],
    # formal + activist
    ["bureaucrat", "activist"],
    # all Tier A + best B
    ["accountant", "scientist", "bureaucrat", "observer", "mourner"],
    # full dark spectrum
    ["cynic", "mourner", "eulogist", "observer"],
    # all 10
    ["cynic", "mourner", "nostalgist", "activist", "accountant",
     "scientist", "naturalist", "eulogist", "observer", "bureaucrat"],
]


# ── hook helpers ─────────────────────────────────────────────────────────────

def apply_hook_op(model, op, arg, hooks):
    layers = model.model.layers
    n = len(layers)
    if op == "scale":
        parts = arg.split(":", 1)
        idx, factor = int(parts[0]), float(parts[1])
        def make_hook(f):
            def hook(module, inp, output):
                if isinstance(output, tuple):
                    return (output[0] * f,) + output[1:]
                return output * f
            return hook
        h = layers[idx].register_forward_hook(make_hook(factor))
        hooks.append(h)
    elif op == "inject":
        parts = arg.split(":", 1)
        target, scale = parts[0], float(parts[1])
        indices = list(range(n)) if target == "all" else [int(target)]
        def make_inject(s):
            def hook(module, inp, output):
                if isinstance(output, tuple):
                    return (output[0] + torch.randn_like(output[0]) * s,) + output[1:]
                return output + torch.randn_like(output) * s
            return hook
        for idx in indices:
            h = layers[idx].register_forward_hook(make_inject(scale))
            hooks.append(h)

def clear_hooks(hooks):
    for h in hooks:
        h.remove()
    hooks.clear()

def do_swap(model, ops):
    for op, arg in ops:
        if op == "swap":
            parts = arg.split(",")
            a, b = int(parts[0]), int(parts[1])
            layers = model.model.layers
            layers[a], layers[b] = layers[b], layers[a]

def undo_swap(model, ops):
    for op, arg in reversed(ops):
        if op == "swap":
            parts = arg.split(",")
            a, b = int(parts[0]), int(parts[1])
            layers = model.model.layers
            layers[a], layers[b] = layers[b], layers[a]


# ── sampling ──────────────────────────────────────────────────────────────────

def sample_token(logits, temp, generated_ids, all_input_ids):
    """Top-p sampling with repetition penalty."""
    if REP_PENALTY != 1.0:
        score = logits.clone()
        penalized = list(all_input_ids) + generated_ids
        for token_id in set(penalized):
            if score[0, token_id] < 0:
                score[0, token_id] *= REP_PENALTY
            else:
                score[0, token_id] /= REP_PENALTY
        logits = score

    logits = logits / max(temp, 0.01)
    probs = F.softmax(logits, dim=-1)

    # top-p filter
    sorted_probs, sorted_indices = torch.sort(probs, descending=True, dim=-1)
    cumulative = torch.cumsum(sorted_probs, dim=-1)
    remove = cumulative - sorted_probs > TOP_P
    sorted_probs[remove] = 0.0
    sorted_probs = sorted_probs / sorted_probs.sum(dim=-1, keepdim=True)

    next_token = torch.multinomial(sorted_probs[0], num_samples=1)
    return sorted_indices[0, next_token]


# ── core generation ───────────────────────────────────────────────────────────

def generate_mixed(base_model, characters, tokenizer, prompt, char_cycle,
                   max_tokens, chunk_size, seed):
    """
    Generate tokens cycling through char_cycle.
    Each character is active for `chunk_size` consecutive tokens.
    No KV cache — full forward pass every token with current char's ops active.
    Simple, correct, slow.
    """
    torch.manual_seed(seed)

    inputs = tokenizer(prompt, return_tensors="pt")
    input_ids = inputs["input_ids"]
    prompt_token_ids = input_ids[0].tolist()

    generated_ids = []
    char_sequence = []

    for step in range(max_tokens):
        char_name = char_cycle[(step // chunk_size) % len(char_cycle)]
        cfg = characters[char_name]
        ops = [tuple(op) for op in cfg["ops"]]
        temp = cfg.get("temp", 0.5)

        hooks = []
        swapped = False

        # rm/noise require model cloning — skip, treat as baseline for that step
        has_destructive = any(op in ("rm", "noise") for op, _ in ops)
        if not has_destructive:
            if any(op == "swap" for op, _ in ops):
                do_swap(base_model, ops)
                swapped = True
            for op, arg in ops:
                if op != "swap":
                    apply_hook_op(base_model, op, arg, hooks)

        # full context every time, no cache
        full_ids = torch.cat([
            input_ids,
            torch.tensor([generated_ids], dtype=torch.long)
        ], dim=1) if generated_ids else input_ids

        with torch.no_grad():
            out = base_model(full_ids, use_cache=False)
            logits = out.logits[:, -1, :]
            next_id = sample_token(logits, temp, generated_ids, prompt_token_ids)

        clear_hooks(hooks)
        if swapped:
            undo_swap(base_model, ops)

        tok = next_id.item()
        if tok == tokenizer.eos_token_id:
            break

        generated_ids.append(tok)
        char_sequence.append(char_name)

    text = tokenizer.decode(generated_ids, skip_special_tokens=True)
    return text, char_sequence


# ── experiment runner ─────────────────────────────────────────────────────────

def combo_key(chars, chunk):
    return f"{'|'.join(chars)}__chunk{chunk}"


def is_done(results, key, prompt):
    return key in results and prompt in results[key]


def save(results, path):
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(results, f, indent=2)
    os.replace(tmp, path)


def p(msg):
    print(msg, flush=True)


def run_experiments(base_model, characters, tokenizer, combos, chunk_sizes,
                    prompts, output_path):
    results = {}
    if os.path.exists(output_path):
        try:
            with open(output_path) as f:
                results = json.load(f)
            p(f"Resuming — {sum(len(v) for v in results.values())} results loaded")
        except Exception as e:
            p(f"Warning: couldn't load {output_path}: {e}")

    total = len(combos) * len(chunk_sizes) * len(prompts)
    done = sum(
        1 for combo in combos for chunk in chunk_sizes for pr in prompts
        if is_done(results, combo_key(combo, chunk), pr)
    )
    p(f"Plan: {len(combos)} combos × {len(chunk_sizes)} chunks × {len(prompts)} prompts = {total} gens")
    p(f"Already done: {done}/{total}\n")

    ci = 0
    for combo in combos:
        for chunk in chunk_sizes:
            key = combo_key(combo, chunk)
            if key not in results:
                results[key] = {}

            label = "+".join(combo)
            if all(is_done(results, key, pr) for pr in prompts):
                p(f"  [{label}] chunk={chunk}: (all done)")
                continue

            p(f"\n{'='*72}")
            p(f"  {label}  chunk={chunk}")
            p(f"{'='*72}")

            for prompt in prompts:
                if is_done(results, key, prompt):
                    p(f"  [{prompt[:40]}]: (cached)")
                    continue

                ci += 1
                t0 = time.time()
                text, char_seq = generate_mixed(
                    base_model, characters, tokenizer,
                    prompt, combo, MAX_TOKENS, chunk, SEED
                )
                dt = time.time() - t0

                results[key][prompt] = {
                    "text": text,
                    "char_sequence": char_seq[:30],  # first 30 token labels
                    "n_tokens": len(char_seq),
                    "dt": round(dt, 1),
                }
                p(f"  [{prompt[:35]}] ({dt:.1f}s, {len(char_seq)}tok)")
                p(f"  {text[:200]}")
                p("")

                save(results, output_path)

    return results


def print_report(results, characters):
    p("\n\n" + "=" * 72)
    p("  MIX REPORT — one sample per combo (chunk=1, 'The ocean is')")
    p("=" * 72)

    prompt = "The ocean is"
    for combo in COMBOS:
        key = combo_key(combo, 1)
        label = "+".join(combo)
        if key in results and prompt in results[key]:
            text = results[key][prompt]["text"]
            p(f"\n  [{label}]")
            p(f"  {text[:300]}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("chars", nargs="?", help="Comma-separated character names")
    parser.add_argument("prompt", nargs="?", help="Prompt string")
    parser.add_argument("--chunk", type=int, default=1)
    parser.add_argument("--all-combos", action="store_true")
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    with open(CHARS_FILE) as f:
        characters = json.load(f)

    p(f"Loading {MODEL}...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL)
    base_model = AutoModelForCausalLM.from_pretrained(
        MODEL, dtype=torch.float16, device_map="cpu", low_cpu_mem_usage=True,
    )
    base_model.eval()
    p(f"Loaded — {len(base_model.model.layers)} layers\n")

    if args.all_combos:
        results = run_experiments(
            base_model, characters, tokenizer,
            COMBOS, CHUNK_SIZES, PROMPTS, args.output
        )
        print_report(results, characters)
        p(f"\nAll results saved to {args.output}")

    elif args.chars and args.prompt:
        combo = [c.strip() for c in args.chars.split(",")]
        p(f"Mixing: {'+'.join(combo)}  chunk={args.chunk}")
        p(f"Prompt: {args.prompt}\n")
        text, char_seq = generate_mixed(
            base_model, characters, tokenizer,
            args.prompt, combo, MAX_TOKENS, args.chunk, SEED
        )
        # annotate with char labels at chunk boundaries
        p(args.prompt + text)
        p(f"\nChar sequence (first 40 tokens): {' '.join(char_seq[:40])}")

    else:
        p("Usage:")
        p("  python mix.py 'cynic,observer,scientist' 'The ocean is'")
        p("  python mix.py --all-combos")


if __name__ == "__main__":
    main()
